name: Java CI

on:
  pull_request:
    branches:
      - master
    tags-ignore:
      - '*.*'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build for JDK ${{ matrix.java }}
    strategy:
      matrix:
        java: [ 17 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Build sources with Gradle
        run: ./gradlew build
        if: |
          !contains(github.event.head_commit.message, '[ci skip]')
  release:
    runs-on: ubuntu-latest
    name: Publish artifacts
    if: github.event_name != 'pull_request'
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Publish sources with Gradle
        run: ./gradlew -PsonatypeUsername=${{ secrets.sonatypeUsername }} -PsonatypePassword=${{ secrets.sonatypePassword }} -PsigningKey="${{ secrets.signingKey }}" -PsigningPassword=${{ secrets.signingPassword }} publish
